### ISSUE TITLE
Unable to run Client and Server on the Same Machine

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patmun/pynetdicom#11]
```
For example try to run both of the examples: storescu and storescp on the same 
machine and you get:

Traceback (most recent call last):
  File "storescu.py", line 54, in <module>
    MyAE = AE(args.aet, 9999, [StorageSOPClass,  VerificationSOPClass], [], ts)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pynetdicom-0.8.1-py2.7.egg/netdicom/applicationentity.py", line 226, in __init__
    self.LocalServerSocket.bind(('', port))
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 48] Address already in use

I assume this is because both want to bind exclusively to the port.
```

Original issue reported on code.google.com by `agrothberg` on 21 Oct 2014 at 2:14

**Comment by naggie** [comment]
I don't think this is an issue any longer, I certainly did run both as part of a unit test.
