### ISSUE TITLE
KeyError: ('Evt11', 'Sta1')

### ISSUE THREAD

**Issue by GoogleCodeExporter** [patmun/pynetdicom#16]
```
For some files I sometimes, but not always get the following error:

Exception in thread Thread-63:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pynetdicom-0.8.1-py2.7.egg/netdicom/DULprovider.py", line 264, in run
    self.SM.Action(evt, self)
  File "/usr/local/Cellar/python/2.7.7_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pynetdicom-0.8.1-py2.7.egg/netdicom/fsm.py", line 481, in Action
    action_name = TransitionTable[(event, self.CurrentState)]
KeyError: ('Evt11', 'Sta1')

This only happens when I create the association as:
 ts = [dicom_file.file_meta.TransferSyntaxUID]
MyAE = AE(aet_client, 0, SupportedTransferSyntax, [], ts)

If I set ts to:
   ts = [
        ExplicitVRLittleEndian,
        ImplicitVRLittleEndian,
        ExplicitVRBigEndian
        ]

then I do not get this error.
```

Original issue reported on code.google.com by `agrothberg` on 29 Oct 2014 at 4:45

**Comment by naggie** [comment]
![image](https://user-images.githubusercontent.com/208440/28611984-98b1a7e6-71e5-11e7-8aa8-2ebba06049e3.png)
I just got the same error. The transfer was otherwise successful.
